# Hamoye 2020 Data Science Internship 
## Introduction to Python for Machine Learning 
### Stage 1 - (Graded Quiz) 
#### Student: Pascal Chisom Okechukwu
##### Date: July 20, 2020 

#### Concatenating two lists

In [16]:
A = [1, 2, 3, 4, 5, 6] 

B = [13, 21, 34]

#A_B = A + B
#A_B

In [17]:
A.extend(B)
A

[1, 2, 3, 4, 5, 6, 13, 21, 34]

#### Creating an identity matrix. Here considering a 3*3 matrix 


In [18]:
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.array([[[1,0,0], [0,1,0], [0,0,1]]])

array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])

#### Wrangling the Fuel Quality Data

In [1]:
import pandas as pd

In [2]:
# Importing the Fuel Quality Data from a github repository 

fuel_data = pd.read_csv('https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv', error_bad_lines = False)
fuel_data.head(8)


record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   
5  f1_fuel_1994_12_2_0_13                 2         1994   
6   f1_fuel_1994_12_2_1_1                 2         1994   
7  f1_fuel_1994_12_2_1_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   
5   e. c. gaston-unit 5                coal       ton        2124933.0   
6      joseph m. farley             nuclear       kgU           2260.0   
7   resondent's portion                coal       ton        5372133.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0            16.590000                      18.59   
1            16.592000                      18.58   
2            24.130000                      39.72   
3            23.950000                      47.21   
4             1.000000                       2.77   
5            23.922000                      44.24   
6             0.064094                      28.77   
7            24.840000                      58.54   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570  
5                         43.25                1.850  
6                          0.00                0.450  
7                         55.13                2.360

In [22]:
fuel_data.describe()

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

In [23]:
# finding the skewness and kurtosis value for the Fuel Quantity Burned column 

fuel_data['fuel_qty_burned'].skew()

15.851495469109503

In [24]:
fuel_data['fuel_qty_burned'].kurtosis()

651.3694501337732

In [25]:
# Checking for missing values 
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [26]:
# checking data set information 

fuel_data.info() 

# It follows that there are 29523 rows or entries

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29523 entries, 0 to 29522
Data columns (total 11 columns):
record_id                       29523 non-null object
utility_id_ferc1                29523 non-null int64
report_year                     29523 non-null int64
plant_name_ferc1                29523 non-null object
fuel_type_code_pudl             29523 non-null object
fuel_unit                       29343 non-null object
fuel_qty_burned                 29523 non-null float64
fuel_mmbtu_per_unit             29523 non-null float64
fuel_cost_per_unit_burned       29523 non-null float64
fuel_cost_per_unit_delivered    29523 non-null float64
fuel_cost_per_mmbtu             29523 non-null float64
dtypes: float64(5), int64(2), object(4)
memory usage: 2.5+ MB


In [27]:
# Checking the correlation of the numarical attributes 

fuel_data.corr(method = 'pearson')

utility_id_ferc1  report_year  fuel_qty_burned  \
utility_id_ferc1                      1.000000     0.093323        -0.057447   
report_year                           0.093323     1.000000         0.012952   
fuel_qty_burned                      -0.057447     0.012952         1.000000   
fuel_mmbtu_per_unit                  -0.066946    -0.110853        -0.080946   
fuel_cost_per_unit_burned            -0.037863     0.013599        -0.018535   
fuel_cost_per_unit_delivered         -0.016414    -0.014043        -0.003551   
fuel_cost_per_mmbtu                   0.006122     0.010261        -0.001896   

                              fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
utility_id_ferc1                        -0.066946                  -0.037863   
report_year                             -0.110853                   0.013599   
fuel_qty_burned                         -0.080946                  -0.018535   
fuel_mmbtu_per_unit                      1.000000                  -0.010034   
fuel_cost_per_unit_burned               -0.010034                   1.000000   
fuel_cost_per_unit_delivered            -0.009039                   0.011007   
fuel_cost_per_mmbtu                     -0.005884                  -0.000437   

                              fuel_cost_per_unit_delivered  \
utility_id_ferc1                                 -0.016414   
report_year                                      -0.014043   
fuel_qty_burned                                  -0.003551   
fuel_mmbtu_per_unit                              -0.009039   
fuel_cost_per_unit_burned                         0.011007   
fuel_cost_per_unit_delivered                      1.000000   
fuel_cost_per_mmbtu                              -0.000109   

                              fuel_cost_per_mmbtu  
utility_id_ferc1                         0.006122  
report_year                              0.010261  
fuel_qty_burned                         -0.001896  
fuel_mmbtu_per_unit                     -0.005884  
fuel_cost_per_unit_burned               -0.000437  
fuel_cost_per_unit_delivered            -0.000109  
fuel_cost_per_mmbtu                      1.000000

In [42]:
# Checking the year with the highest average fuel cost per unit delivered

fuel_data.groupby('fuel_cost_per_unit_delivered')['report_year'].max()

fuel_cost_per_unit_delivered
-874.937        2008
-488.054        2007
-313.410        2004
-174.670        2000
-170.187        2015
                ... 
 1942979.000    1997
 2114508.000    1996
 2255688.000    1997
 7793482.000    1996
 7964521.000    1997
Name: report_year, Length: 16675, dtype: int64

In [41]:
# Checking the fuel type code with the lowest average fuel cost per unit burned

fuel_data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].describe()

count         mean           std     min      25%  \
fuel_type_code_pudl                                                        
coal                  8547.0    67.421830    943.771433    0.00  23.9585   
gas                  11486.0    13.659397    163.286631    0.00   3.2300   
nuclear                818.0  4955.157002  14291.929749    0.00   1.6015   
oil                   8064.0   168.877086   2406.101479    0.00  37.6100   
other                  167.0    18.253856     29.016882 -119.04   2.6325   
waste                  441.0    19.518122     29.988017 -276.08  10.3350   

                         50%       75%         max  
fuel_type_code_pudl                                 
coal                 33.3180  44.66800   44033.320  
gas                   4.6500   6.96000   10490.000  
nuclear              32.5200  50.85525   69785.215  
oil                  68.9455  98.68925  139358.000  
other                 9.0640  20.05500     134.547  
waste                21.9330  32.65000     132.291